### ISSUE TITLE
ThinQApp not running 

### ISSUE THREAD

**Issue by gnowgi** [RUnmesh/ThinQ-Examples#2]
`TypeError: Cannot read property 'node' of undefined
    at /home/nagarjun/dev/ThinQ-Examples/ThinQApp/src/router.js:10:17
    at Layer.handle [as handle_request] (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/layer.js:95:5)
    at /home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/index.js:174:3)
    at router (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/index.js:317:13)
    at /home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:198:13)
    at SendStream.error (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/send/index.js:421:12)
    at next (/home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/send/index.js:763:28)
    at /home/nagarjun/dev/ThinQ-Examples/ThinQApp/node_modules/send/index.js:771:23
    at FSReqWrap.oncomplete (fs.js:153:21)
`

**Comment by coderjedi** [comment]
This happens when we try to access the app's url before IPFS node has started running.After running the command 'npm run start', it takes a few seconds for the IPFS node to get initialzed. After this has completed, you would see messages like "Swarm listening on..." and statements for creation of database tables in the terminal.After this the app should work fine.

**Comment by gnowgi** [comment]
This is the current error:

(node:26436) UnhandledPromiseRejectionWarning: Error: Couldn't listen on any of the servers
